const HomePageCrowdSourcing = () => {
  return (
    <section className="text-white">
      <div className="container px-4 py-12 mx-auto">
        <h2 className="text-3xl font-bold text-gradient mb-8">
          <span className="text-gradient">Inside </span>
          <span className="text-gradient">Our </span>
          <span className="text-gradient">Platform</span>
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h3 className="text-xl font-bold mb-4">Multi-Sensor Data Aggregation</h3>
            <p className="mb-4">We combine data from multiple sensors - satellite, aerial, drone, ground weather - to offer hyper-local geospatial intelligence tailored to your unique needs.</p>
            <ul className="list-disc ml-4 mb-4">
              <li>Cloud-hosted distributed computing framework</li>
              <li>Scalable infrastructure that can handle the large volumes of data generated by crowdsourced sensors</li>
              <li>Common architecture that can be extended to any geospatial application</li>
            </ul>
            <a href="#" className="text-white 
            text-extrabold
            bg-gradient-to-l from-teal-400 via-teal-500 to-teal-600
            hover:bg-gradient-to-br
            focus:ring-4 focus:outline-none focus:ring-teal-300
            dark:focus:ring-teal-800
            font-medium rounded-lg text-sm
            px-5 py-2.5
            text-center">
              Learn More</a>
          </div>
          <div>
            <h3 className="text-xl font-bold mb-4">Machine Learning</h3>
            <p className="mb-4">We specialize in building and deploying machine learning models that can help you make better decisions, faster.</p>
            <ul className="list-disc ml-4 mb-4">
              <li>Model training, tuning, deployment, and inference</li>
              <li>Feature engineering and selection</li>
              <li>Image processing, object detection, image segmentation, and classification</li>
              <li>Data management and storage</li>
            </ul>
            <a href="#" className="text-white 
            text-extrabold
            bg-gradient-to-l from-teal-400 via-teal-500 to-teal-600
            hover:bg-gradient-to-br
            focus:ring-4 focus:outline-none focus:ring-teal-300
            dark:focus:ring-teal-800
            font-medium rounded-lg text-sm
            px-5 py-2.5
            text-center">
              Learn More</a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HomePageCrowdSourcing;
